apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  host: nodejs-postgres.cx0loenncxkh.us-east-1.rds.amazonaws.com
  username: marvin2025
  password: xoQvix-1zebze-buggyn
