name: Deploy Kubernetes Changes

on:
  workflow_dispatch:

jobs:
  deploy_k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name nodejs-eks --region ap-southeast-1

      - name: Create DB Secret
        run: |
          kubectl delete secret db-secret --ignore-not-found
          kubectl create secret generic db-secret \
            --from-literal=host=$(aws rds describe-db-instances --db-instance-identifier nodejs-postgres --query "DBInstances[0].Endpoint.Address" --output text) \
            --from-literal=username=${{ secrets.DB_USER }} \
            --from-literal=password=${{ secrets.DB_PASSWORD }}

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/serviceaccount.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Print ALB DNS
        run: echo "ALB DNS: $(kubectl get ingress nodejs-api-ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')"
