name: Terraform Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ✅ Clean Terraform cache to force correct module version
      - name: Clean Terraform Cache
        run: rm -rf terraform/.terraform terraform/.terraform.lock.hcl

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=terraform init -upgrade

      - name: Check Installed EKS Module Version
        run: |
          echo "Installed EKS module version:"
          grep -A1 "terraform-aws-modules/eks/aws" terraform/.terraform.lock.hcl || echo "Module not found!"

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform -chdir=terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform -chdir=terraform destroy -auto-approve

      # ✅ Only run kubeconfig and kubectl when action = apply
      - name: Update kubeconfig
        if: ${{ github.event.inputs.action == 'apply' }}
        run: aws eks update-kubeconfig --name nodejs-eks --region ${{ env.AWS_REGION }}

      - name: Apply ALB Controller SA
        if: ${{ github.event.inputs.action == 'apply' }}
        run: kubectl apply -f k8s/alb-controller-sa.yaml
